version: 2
jobs:
  build-test-app-background:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: (cd ~/repo/app/background && yarn install)

      - save_cache:
          paths:
            - ~/repo/app/background/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd ~/repo/app/background && yarn test

  build-test-app-content:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: (cd ~/repo/app/content && yarn install)

      - save_cache:
          paths:
            - ~/repo/app/content/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd ~/repo/app/content && yarn test

  build-test-app-popup:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: (cd ~/repo/app/content && yarn install)

      - save_cache:
          paths:
            - ~/repo/app/content/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd ~/repo/app/content && CI=true yarn test

workflows:
  version: 2
  build-test-apps:
    jobs:
      - build-test-app-background
      - build-test-app-content
      - build-test-app-popup