version: 2
jobs:
  build-common:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: (cd ~/repo/packages/common && yarn install)

      - save_cache:
          paths:
            - ~/repo/packages/common/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


  build-test-background:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: (cd ~/repo/packages/background && yarn install)

      - save_cache:
          paths:
            - ~/repo/packages/background/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd ~/repo/packages/background && yarn test

  build-test-content:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: (cd ~/repo/packages/content && yarn install)

      - save_cache:
          paths:
            - ~/repo/packages/content/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd ~/repo/packages/content && yarn test

  build-test-popup:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: (cd ~/repo/packages/content && yarn install)

      - save_cache:
          paths:
            - ~/repo/packages/content/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd ~/repo/packages/content && CI=true yarn test

workflows:
  version: 2
  build-test-packages:
    jobs:
      - build-common
      - build-test-background
      - build-test-content
      - build-test-popup