export const ANNOUNCE_TRANSACTIONS = 'deprecated_ANNOUNCE_TRANSACTIONS'

// content

// popup
export const MESSAGE_ACTIVATE_POPUP = 'MESSAGE_ACTIVATE_POPUP'
export const MESSAGE_READY_FOR_ALLOCATION = 'MESSAGE_READY_FOR_ALLOCATION'
export const MESSAGE_TRANSACTION_ALLOCATED = 'MESSAGE_TRANSACTION_ALLOCATED'
export const MESSAGE_START_PROCESSING_TRANSACTIONS = 'MESSAGE_START_PROCESSING_TRANSACTIONS'
export const MESSAGE_STOP_PROCESSING_TRANSACTIONS = 'MESSAGE_STOP_PROCESSING_TRANSACTIONS'
export const MESSAGE_HIGHLIGHT_TRANSACTIONS = 'MESSAGE_HIGHLIGHT_TRANSACTIONS'

// background
export const MESSAGE_GET_TRANSACTIONS = 'MESSAGE_GET_TRANSACTIONS'
export const MESSAGE_ALLOCATE_TRANSACTION = 'MESSAGE_ALLOCATE_TRANSACTION'

export const MESSAGE_STORE_UPDATED = 'MESSAGE_STORE_UPDATED'